### ISSUE TITLE
"Error Resolving 'hiredis' During Serverless Deployment"

### ISSUE THREAD

**Issue by Yashtoddle** [microsoft/code-push-server#24] opened 2024-10-17 18:31 UTC
while trying to deploying the code to aws server I am getting this error from the Redis package does not contain any package of the name hiredis as the inter dependency can we shift to other version of the Redis to resolve this issue ?

Packaging✘ [ERROR] Could not resolve "hiredis"

    node_modules/redis/lib/parsers/hiredis.js:3:22:
      3 │ var hiredis = require('hiredis');
        │                       ~~~~~~~~~
        ╵                       "./hiredis"

  Use the relative path "./hiredis" to reference the file
  "node_modules/redis/lib/parsers/hiredis.js". Without the leading "./", the path "hiredis" is being
  interpreted as a package path instead.

✖ Stack testing-service-dev failed to deploy (3s)

✖ ServerlessError2: Build failed with 1 error:
node_modules/redis/lib/parsers/hiredis.js:3:22: ERROR: Could not resolve "hiredis"
    at Esbuild._build (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:685:36178)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async before:package:createDeploymentArtifacts (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:685:25113)
    at async PluginManager.runHooks (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:953:9311)
    at async PluginManager.invoke (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:953:10023)
    at async PluginManager.spawn (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:953:10443)
    at async before:deploy:deploy (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:721:65669)
    at async PluginManager.runHooks (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:953:9311)
    at async PluginManager.invoke (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:953:10023)
    at async PluginManager.run (file:///Users/yash/.serverless/releases/4.4.6/package/dist/sf-core.js:953:10813)

**Comment by lucen-ms** [comment] 2024-11-06 13:02
Duplicate of #7

**Closed by lucen-ms** 2024-11-06 13:02 UTC
